/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ACER
 */
public class UserControlPanel extends javax.swing.JFrame {

    /**
     * Creates new form UserControlPanel
     */
       String luser;
    private int totalHarga;
    public UserControlPanel()
    {
    
    }

    /**
     * Creates new form UserControlPanel
     */
    
public UserControlPanel(String loginUser) {
    initComponents();
    this.luser = loginUser;
    String getValue = jLabel1.getText();
    jLabel1.setText(getValue + " : " + loginUser);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        cariBTN = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        namaTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        travel_no = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semarang", "Demak", "Jepara" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Keberangkatan");

        jLabel3.setText("Tujuan");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semarang", "Demak", "Jepara" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        cariBTN.setBackground(new java.awt.Color(204, 204, 204));
        cariBTN.setText("Cari");
        cariBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBTNActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Bayar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Travel", "Keberangkatan", "Tujuan", "Tanggal", "Waktu", "Harga", "Kursi Tersedia"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel6.setText("Nama anda");

        namaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTFActionPerformed(evt);
            }
        });

        jLabel7.setText("Jumlah Kursi");

        jLabel8.setText("PO Travel");

        jLabel9.setText("Jam Berangkat");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("MANAGEMENT TRAVEL MENU");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12.00", "13.00", "14.00", "15.00", "16.00" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(namaTF)
                                                .addComponent(jComboBox1, 0, 131, Short.MAX_VALUE)
                                                .addComponent(jTextField1)))
                                        .addGap(25, 25, 25)
                                        .addComponent(cariBTN))
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(travel_no, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jLabel1)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cariBTN))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jButton2))
                            .addComponent(travel_no, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)))
                .addComponent(jLabel10)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    private int getTotalKursi() {
        // Logika untuk mengambil total kursi dari input pengguna
        // Misalnya dari JTextField yang digunakan untuk input total kursi
        return Integer.parseInt(jTextField1.getText());
    }

   
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   String nama = namaTF.getText();
String keberangkatan = jComboBox1.getSelectedItem().toString();
String tujuan = jComboBox2.getSelectedItem().toString();
int totalKursi = Integer.parseInt(jTextField1.getText());
String travelNo = travel_no.getText();
String berangkat = jComboBox3.getSelectedItem().toString();

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    String databaseURL = "jdbc:mysql://localhost:3306/travelfinal";
    Connection con = DriverManager.getConnection(databaseURL, "root", "");

    // Ambil harga dari database travel_details
    String query = "SELECT harga FROM travel_details WHERE keberangkatan = ? AND tujuan = ?";
    PreparedStatement pst = con.prepareStatement(query);
    pst.setString(1, keberangkatan);
    pst.setString(2, tujuan);

    ResultSet rs = pst.executeQuery();
    int hargaPerKursi = 0;
    if (rs.next()) {
        hargaPerKursi = rs.getInt("harga");
    }

    // Hitung total harga
    int totalHarga = totalKursi * hargaPerKursi;

    // Ambil waktu transaksi (gunakan CURRENT_TIMESTAMP untuk waktu saat ini)
    Timestamp waktuTransaksi = new Timestamp(System.currentTimeMillis());

    // Query untuk menyimpan data transaksi
    String insertQuery = "INSERT INTO transaksi_details (travel_no, keberangkatan, tujuan, waktu, harga, kursi, nama) VALUES (?, ?, ?, ?, ?, ?, ?)";
    PreparedStatement insertPst = con.prepareStatement(insertQuery, Statement.RETURN_GENERATED_KEYS);
    insertPst.setString(1, travelNo);
    insertPst.setString(2, keberangkatan);
    insertPst.setString(3, tujuan);
    insertPst.setTimestamp(4, waktuTransaksi); // Gunakan waktu transaksi saat ini
    insertPst.setInt(5, totalHarga); // Harga total dari transaksi
    insertPst.setInt(6, totalKursi); // Jumlah kursi yang dipesan
    insertPst.setString(7, nama); // Nama pelanggan

    insertPst.executeUpdate();

    // Ambil waktu transaksi yang baru saja disimpan (opsional, jika diperlukan untuk tampilan nota)
    ResultSet generatedKeys = insertPst.getGeneratedKeys();
    String waktuTransaksiStr = "";
    if (generatedKeys.next()) {
        long id = generatedKeys.getLong(1);
        
        // Query untuk mendapatkan waktu transaksi dari transaksi_id (opsional, jika diperlukan untuk tampilan nota)
        String waktuQuery = "SELECT waktu FROM transaksi_details WHERE id = ?";
        PreparedStatement waktuPst = con.prepareStatement(waktuQuery);
        waktuPst.setLong(1, id);

        ResultSet waktuRs = waktuPst.executeQuery();
        if (waktuRs.next()) {
            waktuTransaksiStr = waktuRs.getString("waktu");
        }
    }

    con.close();

    // Tampilkan nota pembelian atau lakukan tindakan lanjutan setelah penyimpanan berhasil
    dispose(); // Tutup frame saat ini
    
    // Munculkan frame NotaPembelian dengan konstruktor yang sesuai
    NotaPembelian np = new NotaPembelian(nama, keberangkatan, tujuan, totalKursi, totalHarga, waktuTransaksiStr);
    np.setLocationRelativeTo(null);
    np.setVisible(true);

} catch (Exception e) {
    e.printStackTrace();
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cariBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBTNActionPerformed
        // TODO add your handling code here:
    String keberangkatan = jComboBox1.getSelectedItem().toString();
    String tujuan = jComboBox2.getSelectedItem().toString();
    String jam = jComboBox3.getSelectedItem().toString();

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        String databaseURL = "jdbc:mysql://localhost:3306/travelfinal";
        Connection con = DriverManager.getConnection(databaseURL, "root", "");

        String query = "SELECT * FROM travel_details WHERE keberangkatan = ? AND tujuan = ? AND waktu = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, keberangkatan);
        pst.setString(2, tujuan);
        pst.setString(3, jam);

        ResultSet rs = pst.executeQuery();
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(0); // Hapus baris

        while (rs.next()) {
            Object[] row = {
                rs.getString("travel_no"),
                rs.getString("keberangkatan"),
                rs.getString("tujuan"),
                rs.getDate("tanggal"),
                rs.getString("waktu"),
                rs.getString("harga"),
                rs.getString("kursi")
            };
            model.addRow(row);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_cariBTNActionPerformed

    private void namaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTFActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable3.getSelectedRow();
    TableModel model = jTable3.getModel();
    
    travel_no.setText(model.getValueAt(selectedRow, 0).toString());
   
    }//GEN-LAST:event_jTable3MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserControlPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cariBTN;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField namaTF;
    private javax.swing.JLabel travel_no;
    // End of variables declaration//GEN-END:variables
}
